let a1 = 10;
let b1 = 23;
let firstName = 'pari';
const perct = 0.4;
let isAppoved = true;
let person = {name: 'kannappan', age: 60};
let person1 = {};
person1.name1 = 'kris';
person1.age1 = 90;
console.log(a1);
console.log(firstName,a1+b1,perct,isAppoved,person,person1); 